version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
           python3 -m pip install --upgrade build
           python3 -m build
  test_pypi_publish:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: init .pypirc
          command: |
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TEST_TOKEN" >> ~/.pypirc
      - run:
          name: deploy to pypi-test
          command: |  # create whl, install twine and publish to Test PyPI
            python3 -m pip install --upgrade build
            python3 -m build
            pip3 install twine
            twine upload --repository testpypi dist/*

  pypi_publish:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: version version
          command: |
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
            python3 version.py
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python3 -m pip install --upgrade build
            python3 -m build
            pip3 install twine
            twine upload dist/*
          environment:
            TWINE_USER: "__token__"
            TWINE_PASSWORD: $PYPY_TOKEN
workflows:
  build_test_publish:
    jobs:
      - build
      - test_pypi_publish:
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
      - pypi_publish:
          requires:
            - build
          filters:
            branches:
              only:
                - main
